import { TheHeader } from '@/components/TheHeader/TheHeader'
import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheFooter } from '@/components/TheFooter/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Test next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='wrapper'>
        <TheHeader/>
        <main className='main'>
        {children}
        </main>
        <footer className='footer'>
        <TheFooter/>
        </footer>
        </div>
        </body>
    </html>
  )
}
